# v1_build_config.yml
#
---
tasks:

- create:
    name: test
    namespace: namespace
    verify_ssl: False
    labels:
      app: test
    output_to_kind: ImageStreamTag
    output_to_name: test:latest
    source_git_uri: "https://test.example.com/test.git"
    source_secret_name: git
    source_type: Git
    strategy_source_strategy_from_kind: ImageStreamTag
    strategy_source_strategy_from_name: nodejs:6
    strategy_source_strategy_from_namespace: openshift
    strategy_type: Source
    triggers:
    - github:
        secret: 8kdCwBdWpup5OydYqXCj
      type: GitHub
    - generic:
        secret: wuve0D41bIFHPU_DzT5-
      type: Generic
    - type: ConfigChange
    - image_change: {}
      type: ImageChange
